### ISSUE TITLE
all my projects locked up and cannot be opened

### ISSUE THREAD

**Issue by flyboarder** [noflo/noflo-ui#446]
Cant open projects from github, on web projects are broken/stuck and will not load

**Comment by bergie** [comment]
@flyboarder check your GitHub token permissions, probably related to #413 and #432

**Comment by flyboarder** [comment]
dont think so, getting a no project found error

**Comment by bergie** [comment]
@flyboarder are the projects private? GitHub returns 404 if you try to access them with a public-only token

**Comment by flyboarder** [comment]
Nope these are created on device on flowhub.io

Matthew Ratzke

**Comment by forresto** [comment]
Was this the SSL issue? Fixed now?

**Comment by flyboarder** [comment]
Not sure what SSL issue you are referring to. I tested lastnight and it was still not working. Does flowhub have a support email?

Matthew Ratzke

**Comment by forresto** [comment]
Test today please, logging in and logging out. Then you might have to then refresh permissions, which requires another login:

![login dance](https://cloud.githubusercontent.com/assets/395307/5378333/60b1d0d2-8057-11e4-95d6-43427db05c28.png)
