### ISSUE TITLE
editing components from a nodejs runtime is broken

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#455]
When selecting "Open" from the circle-menu of a component, I get the orange header bar with the spinner and the label "loading". The developer console shows lots of "WebSocket is already in CLOSING or CLOSED state." with different backtraces. I got ~ 130 such messages.

After I dismiss the header bar, the runtime is disconnected.

**Comment by ensonic** [comment]
Here is a stacktrace for it:
WebSocketRuntime.disconnect (noflo-ui.js:25706)
BaseRuntime.reconnect (noflo-ui.js:25319)
exports.getComponent.c.inPorts.add.process (noflo-ui.js:58285)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5447)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:19903)
Emitter.emit (noflo-ui.js:336)
InPort.handleSocketEvent (noflo-ui.js:5320)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5450)
on (noflo-ui.js:268)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.connect (noflo-ui.js:4960)
(anonymous function) (noflo-ui.js:5452)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:57975)
exports.WirePattern.inPort.process.task (noflo-ui.js:9009)
exports.WirePattern.resumeTaskQ (noflo-ui.js:8647)
exports.WirePattern.inPort.process (noflo-ui.js:9014)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5450)
on (noflo-ui.js:268)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.connect (noflo-ui.js:4960)
(anonymous function) (noflo-ui.js:5452)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:57758)
exports.WirePattern.inPort.process.task (noflo-ui.js:9009)
exports.WirePattern.resumeTaskQ (noflo-ui.js:8647)
exports.WirePattern.inPort.process (noflo-ui.js:9014)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5447)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:19903)
Emitter.emit (noflo-ui.js:336)
InPort.handleSocketEvent (noflo-ui.js:5320)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5450)
on (noflo-ui.js:268)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.connect (noflo-ui.js:4960)
(anonymous function) (noflo-ui.js:5452)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:57539)
exports.WirePattern.inPort.process.task (noflo-ui.js:9009)
exports.WirePattern.resumeTaskQ (noflo-ui.js:8647)
exports.WirePattern.inPort.process (noflo-ui.js:9014)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5450)
on (noflo-ui.js:268)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.connect (noflo-ui.js:4960)
(anonymous function) (noflo-ui.js:5452)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:18265)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5447)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:18265)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5447)
OutPort.send (noflo-ui.js:5442)
(anonymous function) (noflo-ui.js:56482)
exports.WirePattern.inPort.process.task (noflo-ui.js:9009)
exports.WirePattern.resumeTaskQ (noflo-ui.js:8647)
exports.WirePattern.inPort.process (noflo-ui.js:9014)
InPort.handleSocketEvent (noflo-ui.js:5314)
(anonymous function) (noflo-ui.js:5275)
Emitter.emit (noflo-ui.js:336)
InternalSocket.regularEmitEvent (noflo-ui.js:4931)
InternalSocket.send (noflo-ui.js:4982)
(anonymous function) (noflo-ui.js:5447)
OutPort.send (noflo-ui.js:5442)
ListenHash.hashChange (noflo-ui.js:11877)
__bind (noflo-ui.js:11810)

**Comment by bergie** [comment]
Should be fixed via #457

**Comment by ryedin** [comment]
So this doesn't 100% resolve the issue on my end. On first attempt at loading a subgraph I still get the orange 'Loading...' header bar that hangs. Eventually I get the following error in the browser console:

```
WebSocket connection to 'wss://api.flowhub.io/primus/?_primuscb=1425952125910-1' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

However, now if I refresh, the subgraph I was attempting to load is visible, and then navigating back and even opening other subgraphs and components seems to work fine.

Component loading does work better, but not on first load (for my setup).

**Comment by ensonic** [comment]
@ryedin, did this ever work? Maybe better file this as a new bug (and reference this one if you want). I think it is a separate issue.

**Comment by ryedin** [comment]
@ensonic before your PR here https://github.com/noflo/noflo-ui/pull/457, component loading never worked for me against my nodejs runtime. Now it does, but I have to refresh the page after attempting to open a component, so seemed related.

new issue opened here: https://github.com/noflo/noflo-ui/issues/459
